# Generated by Django 4.0.2 on 2022-02-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfeedback',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_coment', to='book.book'),
        ),
    ]
